# Generated by Django 4.2.4 on 2023-09-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(editable=False, max_length=148, unique=True, verbose_name='URL-имя'),
        ),
    ]
